bootstrap_metrics: false
df_test_path: null
hidden_channels: 128
log_only_loss_at_stages: !!python/tuple
- !!python/object/apply:builtins.getattr
  - &id001 !!python/name:massspecgym.models.base.Stage ''
  - TRAIN
lr: 0.0001
no_mces_metrics_at_stages: !!python/tuple
- !!python/object/apply:builtins.getattr
  - *id001
  - VAL
weight_decay: 0.0
