at_ks: !!python/tuple
- 1
- 5
- 20
bootstrap_metrics: false
df_test_path: null
hidden_channels: 128
log_only_loss_at_stages: !!python/tuple
- !!python/object/apply:builtins.getattr
  - &id001 !!python/name:massspecgym.models.base.Stage ''
  - TRAIN
lr: 0.0001
myopic_mces_kwargs: null
no_mces_metrics_at_stages: !!python/tuple
- !!python/object/apply:builtins.getattr
  - *id001
  - VAL
out_channels: 4096
weight_decay: 0.0
